spring.profiles.active=${ENV:local}
server.port=9600

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.druid.initial-size=0
spring.datasource.druid.max-active=1
spring.datasource.druid.min-idle=0

spring.data.redis.host=${REDIS_URL}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.database=${REDIS_DB}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=1
spring.data.redis.lettuce.pool.min-idle=0

mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
mybatis-plus.global-config.db-config.id-type=ASSIGN_ID

sa-token.token-name=Authorization

logging.level.root=info

aliyun.sms.key=${ALIYUN_SMS_KEY}
aliyun.sms.secret=${ALIYUN_SMS_SECRET}